title: Orphic FM
url: "https://orphic.fm"
description: Music is semi-random math (with structure)
show_downloads: false
plugins:
  - jekyll-redirect-from

collections:
  creations:
    output: true
    permalink: /creation/:path/

navigation:
  - title: Home
    url: /
social:
  github: balch
